# Generated by Django 3.1.2 on 2020-11-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_submittedassignment_student'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_subject', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='assignmentfile',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentfiles_assignment', to='events.assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_event', to='events.event'),
        ),
    ]
