# Generated by Django 3.1.2 on 2020-11-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_teacher',
        ),
    ]
