# Generated by Django 3.0.7 on 2020-11-12 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_department_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='requesting_users',
            field=models.ManyToManyField(blank=True, related_name='department_requesting_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
