# Generated by Django 3.1.2 on 2020-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='join_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
